FROM node:14

# Create app directory
RUN mkdir -p /usr/src/app/dashboard
WORKDIR /usr/src/app/dashboard

# Install app dependencies
COPY ./dashboard .
RUN yarn build
ENV PATH="./node_modules/.bin:${PATH}"

EXPOSE 3000

# Command to run the app
CMD [ "serve", "-s", "build" ]
