version: "3"
services:
  osrs-progress-tracker-backend-app:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENV: "prod"
    volumes:
      - ./:/usr/src/app/
    entrypoint:
      - "/bin/bash"
    container_name: "osrs-progress-tracker-backend-app"
    image: "osrs-progress-tracker/backend"

  osrs-progress-tracker-frontend-app:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.dashboards.prod
    ports:
      - "3000:3000"
    environment:
      ENV: "prod"
    volumes:
      - ./dashboard:/usr/src/app/dashboard
    entrypoint:
      - "/bin/bash"
    container_name: "osrs-progress-tracker-frontend-app"
    image: "osrs-progress-tracker/frontend"
